name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build -t data-analyst .

    - name: Tag and push Docker image to GCR
      run: |
        docker tag data-analyst gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-analyst:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-analyst:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy data-analyst-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-analyst:latest \
          --platform managed \
          --region europe-north1 \
          --allow-unauthenticated \
          --set-env-vars "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}"
    - name: Debug GCP Project ID
      run: |
        echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"